name = "Mainroad"
license = "GPLv2"
licenselink = "//github.com/vimux/mainroad/blob/master/LICENSE.md"
description = "Mainroad is a responsive, clean and content-focused Hugo theme."
homepage = "//github.com/vimux/mainroad/"
tags = ["blog", "responsive", "widgets", "rss", "disqus", "wordpress"]
features = ["blog", "responsive", "widgets", "rss", "disqus", "wordpress"]
min_version = 0.19

[author]
  name = "Vimux"
  homepage = "//github.com/vimux"

# If porting an existing theme
[original]
  name = "MH Magazine lite"
  homepage = "//wordpress.org/themes/mh-magazine-lite/"
  repo = "//themes.trac.wordpress.org/browser/mh-magazine-lite/2.5.6"